version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./src/main/resources:/app/resources
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/barber
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: barber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
